version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-go1.14
      - test-go1.13
      - test-go1.12

jobs:
  test-go1.14: &test-template
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run:
          name: Install golangci-lint
          command: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.30.0
            golangci-lint version
      - run:
          name: Lint
          command: golangci-lint run
      - run:
          name: Test
          command: go test -cover -v ./...
  test-go1.13:
    <<: *test-template
    docker:
      - image: circleci/golang:1.13
  test-go1.12:
    <<: *test-template
    docker:
      - image: circleci/golang:1.12
